@hostname=localhost
@port=7291
@host={{hostname}}:{{port}}

###

GET https://{{host}}/financialgoal
Accept: application/json

###

POST https://{{host}}/financialgoal
Content-Type: application/json

{
  "title": "test 2 from visual studio http requests",
  "targetQuantity": 20000
}